### ISSUE TITLE
Create a create-soroban-dapp boilerplate based on create-react-app (with next)

### ISSUE THREAD

**Issue by esteblock** [paltalabs/create-soroban-dapp#6]

**Comment by benjaminsalon** [comment]
- [ ] [Initial Boilerplate Framework settings](https://github.com/paltalabs/create-soroban-dapp/issues/5)
- [ ] [Creating contracts for backend](https://github.com/paltalabs/create-soroban-dapp/issues/2)
- [ ] [Contracts Integration](https://github.com/paltalabs/create-soroban-dapp/issues/4)
- [ ] [Front-end optimization and styling](https://github.com/paltalabs/create-soroban-dapp/issues/3)
- [ ] [Documentation](https://github.com/paltalabs/create-soroban-dapp/issues/1)

**Comment by esteblock** [comment]
Close because we have all in different issues
